name: Lens cape
favicon: null
layout_spectrum: 0.5277325238566846
typography_spectrum: 0.2474964966531843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3912109376396984
  lightness: 0.5549387100618333
  saturation: 0.37493987916968763
  rhythmicContrast: 0.4144361966755241
purpose: []
